# Site settings
title: "Hello, my name is Michael Saul."
header-img: img/home-bg.jpg
email: michael.saul@gmail.com
description: "Welcome to michaelsaul.me, the web page of Michael Saul"
baseurl: ""
url: "michaelsaul.me"
twitter_username: michael_saul
github_username:  michaelsaul
facebook_username:  michael.saul
linkedin_username: michaelsaul01

#analytics:
#  provider: google
#  google:
#    tracking_id: "UA-62107216-1"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-sitemap
